hris/urls.py
from django.conf.urls import url
from hris.views import home
from hris.views import EmployeeCreateView
from hris.views import EmployeeDetailView
from hris.views import EmployeeListView
from hris.views import EmployeeUpdateView
from hris.views import EmployeeDeleteView

urlpatterns = [

    url(
        r'employee/update/(?P<pk>\d+)/$',
        EmployeeUpdateView.as_view(),
        name = "hris_employee_update"
    ),
    url(
        r'employee/delete/(?P<pk>\d+)/$',
        EmployeeDeleteView.as_view(),
        name = "hris_employee_delete"
    ),
    url(
        r'employee/detail/(?P<pk>\d+)/$',
        EmployeeDetailView.as_view(),
        name = "hris_employee_detail"
    ),
    url(
        r'employee/create/$',
        EmployeeCreateView.as_view(),
        name = "hris_employee_create"
    ),
    url(
        r'employee/$',
        EmployeeListView.as_view(),
        name = "hris_employee_list"
    ),
    url(
        r'$',
        home,
        name = "hris_home"
    ),
]

mumscrum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# from django.contrib.auth import login
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
from mumscrum.views.page_not_found_view import page_not_found_view
from mumscrum.views.bad_request_view import bad_request_view
from mumscrum.views.permission_denied_view import permission_denied_view
from mumscrum.views.server_error_view import server_error_view

handler400 = bad_request_view
handler404 = page_not_found_view
handler403 = permission_denied_view
handler500 = server_error_view

urlpatterns = [
    url(
        r'^login/$',
        'hris.views.auth.login',
        {'template_name' : 'auth/login.html'},
        name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(
        r'^reset/$',
        password_reset,
        {'template_name' : 'auth/password_reset_form.html'},        
        name='password_reset',
    ),

    url(
        r'^reset/done/$',
        password_reset_done,
        {'template_name' : 'auth/password_reset_done.html'},
        name='password_reset_done'
    ),    

    url(
        r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, 
        {'post_reset_redirect' : '/reset/complete/', 
            'template_name' : 'auth/password_reset_confirm.html' },
        name="password_reset_confirm"
    ),

    url(
        r'^reset/complete/$',
        password_reset_complete,
        {'template_name' : 'auth/password_reset_complete.html' },
        name='password_reset_complete'
    ),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^hris/', include("hris.urls")),
    url(r'^scrum/', include("scrum.urls")),
    url(r'^report/', include("report.urls")),
    url(r'^tasks/', include("emptask.urls")),
    url(r'^$', 'mumscrum.views.home', name='home'),
    # serving media files
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
    ]

scrum/urls.py
from django.conf.urls import url
from scrum.views import ProductBacklogCreateView
from scrum.views import ProductBacklogDetailView
from scrum.views import ProductBacklogListView
from scrum.views import ProductBacklogUpdateView
from scrum.views import ProductBacklogDeleteView

from scrum.views import ReleaseBacklogCreateView
from scrum.views import ReleaseBacklogUpdateView
from scrum.views import ReleaseBacklogDeleteView
from scrum.views import ReleaseBacklogDetailView
from scrum.views import ReleaseBacklogListView
from scrum.views import ReleaseBacklogStoryDeleteView
from scrum.views import ReleaseBacklogAssignScrumMasterView

from scrum.views import home as scrum_home

from scrum.views import UserStoryCreateView
from scrum.views import UserStoryDeleteView
from scrum.views import UserStoryDetailView
from scrum.views import UserStoryUpdateView
from scrum.views import UserStoryToReleaseView
from scrum.views import UserStoryToSprintView
from scrum.views import UserStoryAssignTesterView
from scrum.views import UserStoryAssignDeveloperView

from scrum.views import SprintCreateView
from scrum.views import SprintDeleteView
from scrum.views import SprintUpdateView
from scrum.views import SprintStoryDeleteView
from scrum.views import SprintStartView
from scrum.views import SprintEndView

urlpatterns = [
    url(
        r'product-backlog/update/(?P<pk>\d+)/$',
        ProductBacklogUpdateView.as_view(),
        name = "scrum_product_backlog_update"
    ),
    url(r'product-backlog/delete/(?P<pk>\d+)/$',
        ProductBacklogDeleteView.as_view(),
        name = "scrum_product_backlog_delete"
    ),
    url(
        r'product-backlog/detail/(?P<pk>\d+)/$',
        ProductBacklogDetailView.as_view(),
        name = "scrum_product_backlog_detail"
    ),
    url(
        r'product-backlog/(?P<pk>\d+)/$',
        ProductBacklogDetailView.as_view(),
        name = "scrum_product_backlog"
    ),
    url(
        r'product-backlog/create/$',
        ProductBacklogCreateView.as_view(),
        name = "scrum_product_backlog_create"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/move-stories/$',
        UserStoryToReleaseView.as_view(),
        name = "scrum_user_story_to_release"
    ),
    url(
        r'product-backlog/$',
        ProductBacklogListView.as_view(),
        name = "scrum_product_backlog_list"
    ),
    # release_backlog
    url(
        r'product-backlog/(?P<product_id>\d+)/release-backlog/update/(?P<pk>\d+)/$',
        ReleaseBacklogUpdateView.as_view(),
        name = "scrum_release_backlog_update"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/release-backlog/delete/(?P<pk>\d+)/$',
        ReleaseBacklogDeleteView.as_view(),
        name = "scrum_release_backlog_delete"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/release-backlog/create/$',
        ReleaseBacklogCreateView.as_view(),
        name = "scrum_release_backlog_create"
    ),
    url(
        r'release-backlog/detail/(?P<pk>\d+)/$',
        ReleaseBacklogDetailView.as_view(),
        name = "scrum_release_backlog_detail"
    ),
    url(
        r'release-backlog/assign-scrum-master/(?P<pk>\d+)/$',
        ReleaseBacklogAssignScrumMasterView.as_view(),
        name = "scrum_release_backlog_assign_scrum_master"
    ),
    url(
        r'release-backlog/user-story/delete/(?P<pk>\d+)/$',
        ReleaseBacklogStoryDeleteView.as_view(),
        name = "scrum_release_backlog_user_story_delete"
    ),
    url(
        r'release-backlog/$',
        ReleaseBacklogListView.as_view(),
        name = "scrum_release_backlog_list"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/user-story/create/$',
        UserStoryCreateView.as_view(),
        name = "scrum_user_story_create"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/user-story/delete/(?P<pk>\d+)/$',
        UserStoryDeleteView.as_view(),
        name = "scrum_user_story_delete"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/user-story/detail/(?P<pk>\d+)/$',
        UserStoryDetailView.as_view(),
        name = "scrum_user_story_detail"
    ),
    url(
        r'product-backlog/(?P<product_id>\d+)/user-story/update/(?P<pk>\d+)/$',
        UserStoryUpdateView.as_view(),
        name = "scrum_user_story_update"
    ),
    url(
        r'release-backlog/(?P<release_id>\d+)/move-stories/$',
        UserStoryToSprintView.as_view(),
        name = "scrum_user_story_to_sprint"
    ),
    url(
        r'release-backlog/(?P<release_id>\d+)/sprint/create/$',
        SprintCreateView.as_view(),
        name = "scrum_sprint_create"
    ),
    url(
        r'sprint/delete/(?P<pk>\d+)/$',
        SprintDeleteView.as_view(),
        name = "scrum_sprint_delete"
    ),
    url(
        r'sprint/update/(?P<pk>\d+)/$',
        SprintUpdateView.as_view(),
        name = "scrum_sprint_update"
    ),
    url(
        r'sprint/start/(?P<pk>\d+)/$',
        SprintStartView.as_view(),
        name = "scrum_sprint_start"
    ),
    url(
        r'sprint/end/(?P<pk>\d+)/$',
        SprintEndView.as_view(),
        name = "scrum_sprint_end"
    ),
    url(
        r'sprint/user-story/delete/(?P<pk>\d+)/$',
        SprintStoryDeleteView.as_view(),
        name = "scrum_sprint_user_story_delete"
    ),
    url(
        r'user-story/assign-developer/(?P<pk>\d+)/$',
        UserStoryAssignDeveloperView.as_view(),
        name = "scrum_user_story_assign_developer"
    ),
    url(
        r'user-story/assign-tester/(?P<pk>\d+)/$',
        UserStoryAssignTesterView.as_view(),
        name = "scrum_user_story_assign_tester"
    ),
    url(
        r'$',
        scrum_home,
        name = "scrum_home"
    ),
]

scrum/models/release_backlog.py
from django.db import models
from hris.models import Employee
from scrum.models import ProductBacklog

class ReleaseBacklog(models.Model):
    name = models.CharField(
        max_length=50,
        null=False, blank=False
    )
    scrum_master = models.ForeignKey(Employee, null=True, blank=True)
    product_backlog = models.ForeignKey(ProductBacklog, null=True, blank=True)
    # object CRUD related infomation
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    created_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="release_backlog_created_by"
    )
    updated_on = models.DateTimeField(auto_now=True, auto_now_add=False)
    updated_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="release_backlog_updated_by"
    )
    is_deleted = models.BooleanField(default=False)
    deleted_on = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    deleted_by = models.ForeignKey(
        Employee, null=True,
        blank=True, related_name="release_backlog_deleted_by"
    )

    class Meta:
        app_label = 'scrum'
        unique_together = ['product_backlog', 'name']

    def __unicode__(self):
        return self.name

scrum/models/sprint.py
from django.db import models
from hris.models import Employee
from scrum.models import ReleaseBacklog

class Sprint(models.Model):
    name = models.CharField(
        max_length=50,
        null=False, blank=False,
        help_text = "Sprint name should be in order like Sprint-1, Sprint-2, and so on"
    )
    release_backlog = models.ForeignKey(
        ReleaseBacklog, null=False,
        blank=False
    )
    sprint_start = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    sprint_end = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    # object CRUD related infomation
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    created_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="sprint_created_by"
    )
    updated_on = models.DateTimeField(auto_now=True, auto_now_add=False)
    updated_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="sprint_updated_by"
    )
    is_deleted = models.BooleanField(default=False)
    deleted_on = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    deleted_by = models.ForeignKey(
        Employee, null=True,
        blank=True, related_name="sprint_deleted_by"
    )

    class Meta:
        app_label = 'scrum'

    def __unicode__(self):
        return self.name

    @property
    def product_backlog(self):
        return self.release_backlog.product_backlog
    

scrum/models/user_story.py
from django.db import models
from scrum.models.product_backlog import ProductBacklog
from scrum.models.release_backlog import ReleaseBacklog
from scrum.models.sprint import Sprint
from hris.models import Employee

class UserStory(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(max_length=2000, blank=True, null=True)
    assiged_developer = models.ForeignKey(
        Employee, null=True,
        blank=True, related_name="userstory_assiged_developer"
    )
    developer_effort = models.IntegerField(null=True, blank=True)
    assiged_tester = models.ForeignKey(
        Employee, null=True,
        blank=True, related_name="userstory_assiged_tester"
    )
    tester_effort = models.IntegerField(null=True, blank=True)
    product_backlog = models.ForeignKey(ProductBacklog, null=True, blank=True)
    release_backlog = models.ForeignKey(ReleaseBacklog, null=True, blank=True)
    sprint = models.ForeignKey(Sprint, null=True, blank=True)

    # object CRUD related infomation
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    created_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="userstory_created_by"
    )
    updated_on = models.DateTimeField(auto_now=True, auto_now_add=False)
    updated_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="userstory_updated_by"
    )
    is_deleted = models.BooleanField(default=False)
    deleted_on = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    deleted_by = models.ForeignKey(
        Employee, null=True,
        blank=True, related_name="userstory_deleted_by"
    )

    def __unicode__(self):
        return self.title

    class Meta:
        app_label = 'scrum'

hris/views/home.py
from django.shortcuts import render

def home(request):
    return render(request, "hris_home.html", {})

mumscrum/views/home.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html", {})

scrum/views/home.py
from django.shortcuts import render

def home(request):
    return render(request, "scrum/home.html", {})

scrum/views/product_backlog_create_view.py
from django.views.generic.edit import CreateView
from scrum.models import ProductBacklog
from django.contrib import messages
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.core.urlresolvers import reverse_lazy

class ProductBacklogCreateView(CreateView):
    model = ProductBacklog
    fields = ('name',)
    success_url = reverse_lazy('scrum_product_backlog_list')

    @method_decorator(employee_role_required("product_owner"))
    def dispatch(self,  *args, **kwargs):
        return super(ProductBacklogCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user.employee
        form.instance.created_by = self.request.user.employee
        form.instance.updated_by = self.request.user.employee
        return super(ProductBacklogCreateView, self).form_valid(form)

    def get_success_url(self, *args, **kwargs):
        messages.add_message(self.request, messages.SUCCESS,\
            'New Prodcuct Backlog successfully added')
        return reverse_lazy('scrum_product_backlog_list')

scrum/views/product_backlog_delete_view.py
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import DeleteView
from scrum.models import ProductBacklog
from django.shortcuts import redirect
from django.contrib import messages
from django.utils import timezone

class ProductBacklogDeleteView(DeleteView):
    model = ProductBacklog
    success_url = reverse_lazy('scrum_product_backlog_list')

    @method_decorator(employee_role_required("product_owner"))
    def dispatch(self, *args, **kwargs):
        return super(ProductBacklogDeleteView, self).dispatch(*args, **kwargs)

    def post(self, *args, **kwargs):
        product_backlog_object = self.get_object()
        product_backlog_object.updated_by = self.request.user.employee
        product_backlog_object.is_deleted = True
        product_backlog_object.deleted_by = self.request.user.employee
        product_backlog_object.deleted_on = timezone.now()
        product_backlog_object.save()
        messages.add_message(self.request, messages.SUCCESS, 'New employee successfully added')        
        return redirect(self.success_url)

scrum/views/product_backlog_detail_view.py
from django.views.generic import DetailView
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from scrum.models import ProductBacklog
from scrum.services import ProductBacklogService
from scrum.services import ReleaseBacklogService
from scrum.services import UserStoryService

class ProductBacklogDetailView(DetailView):
    model = ProductBacklog

    @method_decorator(employee_role_required("product_owner", "scrum_master"))
    def dispatch(self, *args, **kwargs):
        return super(ProductBacklogDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductBacklogDetailView, self).get_context_data(**kwargs)
        # import pdb; pdb.set_trace()
        context['user_stories'] = UserStoryService.product_backlog_stories(
            self.get_object().id
        )
        context['release_list'] = ReleaseBacklogService.product_backlog_releases(
            self.get_object().id
        ).order_by('-id')
        return context

scrum/templates/scrum/productbacklog_detail.html
{% extends "base.html"%}
{% block title %}{% endblock %}
{% load staticfiles %}
{% load employee_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/flat/blue.css' %}">
{% endblock %}
<!-- This is page header and bredcrumb -->
{% block content_header %}
    <section class="content-header">
      <h1>
        SCRUM
        <small>Control Panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'scrum_home' %}"><i class="fa fa-dashboard"></i> SCRUM</a></li>
        <li><a href="{% url 'scrum_product_backlog_list' %}"> Product Backlogs</a></li>
        {% if object %}
        <li><a href="{% url 'scrum_product_backlog' object.id %}">{{object.name}}</a></li>
        {% endif %}
        <li class="active">Detail</li>
      </ol>
    </section>
{% endblock %}
<!-- Add your content here -->
{% block content %}
          
  <div class="row">
    <div class="col-md-7">
      <h3>{{object.name}}

    {% ifrole PRODUCT_OWNER %}
        <a href="{% url 'scrum_release_backlog_create' object.id %}" title="add-release" data-toggle="tooltip" class="pull-right"><i class="fa  fa-plus-circle icon-add"></i></a>
    {% endifrole %}
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7" id="release-accordion">
        {% include "scrum/releasebacklog_list.html" %}
    </div>
    <div class="col-md-5">
      {% ifrole PRODUCT_OWNER %}
      {% include "scrum/productbacklog_stories.html" %}
      {% endifrole %}
    </div><!-- /.col -->
  </div><!-- /.row -->
{% endblock %} 
<!-- Add your javascript plugin src or code content here -->
{% block footer_js %}
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        //Enable iCheck plugin for checkboxes
        //iCheck for checkbox and radio inputs


        $('.mailbox-messages input[type="checkbox"]').iCheck({
          checkboxClass: 'icheckbox_flat-blue',
          radioClass: 'iradio_flat-blue'
        });

        //Enable check and uncheck all functionality
        $(".checkbox-toggle").click(function () {
          console.log("hello");
          var clicks = $(this).data('clicks');
          if (clicks) {
            //Uncheck all checkboxes
            $(this).closest('div').find("input[type='checkbox']").iCheck("uncheck");
            $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
          } else {
            //Check all checkboxes
            $(this).closest('div').find("input[type='checkbox']").iCheck("check");
            $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
          }
          $(this).data("clicks", !clicks);
        });

        //Handle starring for glyphicon and font awesome
        $(".mailbox-star").click(function (e) {
          e.preventDefault();
          //detect type
          var $this = $(this).find("a > i");
          var glyph = $this.hasClass("glyphicon");
          var fa = $this.hasClass("fa");

          //Switch states
          if (glyph) {
            $this.toggleClass("glyphicon-star");
            $this.toggleClass("glyphicon-star-empty");
          }

          if (fa) {
            $this.toggleClass("fa-star");
            $this.toggleClass("fa-star-o");
          }
        });
      });
</script>

{% endblock %}

scrum/templates/scrum/releasebacklog_stories.html
{% load scrum_tags %}
{% load employee_tags %}
<form action="{% url 'scrum_user_story_to_sprint' release.id %}" method="POST">
  {% csrf_token %}
  <div class="box box-solid">
    <div class="box-header header-shadow">
      <h3 class="box-title">Stories</h3>
      <div class="box-tools">
        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div><!-- /.box-header -->
    <div class="box-body no-padding body-shadow">
      <div class="mailbox-controls">
        <!-- Check all button -->
        {% ifrole SCRUM_MASTER PRODUCT_OWNER %}
        <span class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></span>
        <div class="btn-group">
          <select name="sprint_id" class="btn btn-default btn-sm" onchange="this.form.submit()">
            <option>---- Select Sprint ---</option>
            {% for sprint in release.sprint_set.all %}
              {% if not sprint.is_deleted %}
                <option value="{{sprint.id}}">{{sprint.name}}</option>
              {% endif %}
            {% endfor %}
          </select>
        </div><!-- /.btn-group -->
        {% endifrole %}

        {% if release %}
        <!--  -->
          {% load_release_stories release user %}
        {% endif %}
    </div><!-- /.box-body -->
    </div>
  </div><!-- /. box -->
</form>

scrum/templates/scrum/sprint_list.html
{% load employee_tags %}
<div class="box box-solid ">
  <div class="box-header header-shadow">
    <h3 class="box-title">Sprints&nbsp;&nbsp;
      <a href="{% url 'scrum_sprint_create' release.id %}"><i class="fa fa-plus-circle icon-add-small"></i></a>&nbsp;&nbsp;
    </h3>
    <div class="box-tools">
      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body body-shadow">
    <div class="panel-group" id="accordion-2">
      {% for sprint in release.sprint_set.all %}
        {% if not sprint.is_deleted %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion-2" href="#sprint{{sprint.id}}"> {{sprint}}&nbsp;&nbsp;</a>
                {% ifrole SCRUM_MASTER PRODUCT_OWNER %}
                  <div class="controls pull-right" >                    
                    {% if not sprint.sprint_start %}
                      <a href="{% url 'scrum_sprint_start' sprint.id %}" class="btn btn-default-sm">Start Sprint</a>
                    {% elif not sprint.sprint_end %}
                      <a href="{% url 'scrum_sprint_end' sprint.id %}" class="btn btn-default-sm">End Sprint</a>
                    {% endif %}
                    <a href="{% url 'scrum_sprint_update' sprint.id %}"><i class="fa fa-pencil icon-edit-small" title="Edit" data-toggle="tooltip"></i></a>&nbsp;&nbsp;
                    <a href="{% url 'scrum_sprint_delete' sprint.id %}"><i class="fa fa-trash icon-delete-small" title="Delete" data-toggle="tooltip"></i></a>
                  </div>
                {% endifrole %}
            </h4>
          </div>
          <div id="sprint{{sprint.id}}" class="panel-collapse collapse">
        {% ifrole PRODUCT_OWNER SCRUM_MASTER %}
            <div class="panel-body">
              {% include "scrum/sprint_stories.html" %}
            </div>
        {% endifrole %}
          </div>
        </div>
        {% endif %}
      {% endfor %}
    </div>
  </div><!-- /.box-body -->
</div><!-- /. box -->

scrum/templates/scrum/sprint_stories.html
{% load prettytimes_tags %}
{% load employee_tags %}

<div class="table-responsive mailbox-messages">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th></th>
        <th width="80"><small style="font-size: 10px;">Developer</small></th>
        <th width="80"><small style="font-size: 10px;">Tester</small></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for story in sprint.userstory_set.all %}
      <tr>
        <td class="mailbox-subject"><a href="{% url 'scrum_user_story_detail' story.product_backlog.id story.id %}"><b>{{story.title}}</b></a> - {{story.description|truncatechars:30}}<br/>{{story.created_on | relative_time }}, by <a href="{% url 'hris_employee_detail' story.created_by.id %}">{{story.created_by.name}}</a></td>
        <td class="no-margin developer-image-bg"  width="60">
        {% ifrole SCRUM_MASTER %}
          <a href="{% url 'scrum_user_story_assign_developer' story.id %}"  data-toggle="tooltip" title="Developer:&nbsp;{% if story.assiged_developer %}{{story.assiged_developer.name}}{% else %}Click to assign{% endif %}">
        {% endifrole %}
            {% if story.assiged_developer %}
              {% profile_image story.assiged_developer "developer-info-image" %}
              <figcaption><small><a  title="More about&nbsp;{{story.assiged_developer.name}}" data-toggle="tooltip" href="{% url 'hris_employee_detail' story.assiged_developer.id  %}"><i class="fa fa-info-circle icon-edit-samll"></i></a></small></figcaption>
            {% else %}
            <div class="developer-info-image">            
              <i class="fa fa-plus-circle icon-add-small"></i>
            </div>
            {% endif %}
        {% ifrole SCRUM_MASTER %}
          </a>
        {% endifrole %}
        </td>
        <td class="no-margin tester-image-bg" width="60">
        {% ifrole SCRUM_MASTER %}
          <a href="{% url 'scrum_user_story_assign_tester' story.id %}" data-toggle="tooltip" title="Tester:&nbsp;{% if story.assiged_tester %}{{story.assiged_tester.name}}{% else %}Click to assign{% endif %}">
        {% endifrole %}
          {% if story.assiged_tester %}
            {% profile_image story.assiged_tester "developer-info-image" %}
            <figcaption><small><a  title="More about&nbsp;{{story.assiged_tester.name}}" data-toggle="tooltip" href="{% url 'hris_employee_detail' story.assiged_tester.id  %}"><i class="fa fa-info-circle icon-edit-samll"></i></a></small></figcaption>
          {% else %}
          <div class="developer-info-image">            
            <i class="fa fa-plus-circle icon-add-small"></i>
          </div>
          {% endif %}
        {% ifrole SCRUM_MASTER %}
          </a>
        {% endifrole %}
        </td>
        <td class="mailbox-attachment">
      {% ifrole SCRUM_MASTER %}
          <a href="{% url 'scrum_sprint_user_story_delete' story.id %}" title="Delete" data-toggle="tooltip"><i class="fa fa-trash icon-delete-small" title="Delete" data-toggle="tooltip"></i></a>
      {% endifrole %}
        </td>
      </tr>
      {% empty %}
        <tr>
          <td>
            No user stories available.
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table><!-- /.table -->
</div><!-- /.mail-box-messages -->