emptask/urls.py
from django.conf.urls import url
from emptask.views import EmployeeTaskTemplateView
from emptask.views import DevelopmentTaskDetailView
from emptask.views import TestingTaskDetailView
from emptask.views import DevelopmentEstimateView
from emptask.views import TestEstimateView
from emptask.views import DevelopmentEstimateCreateView
from emptask.views import TestingEstimateCreateView
from emptask.views import TestingEstimateUpdateView
from emptask.views import DevelopmentEstimateUpdateView

urlpatterns = [
    url(r'test/detail/(?P<pk>\d+)/$',
        TestingTaskDetailView.as_view(),
        name="emptask_testing_task_detail"
    ),
    url(r'dev/detail/(?P<pk>\d+)/$',
        DevelopmentTaskDetailView.as_view(),
        name="emptask_development_task_detail"
    ),
    url(r'dev/estimate/(?P<pk>\d+)/$',
        DevelopmentEstimateView.as_view(),
        name="emptask_development_estimate"
    ),
    url(r'test/estimate/(?P<pk>\d+)/$',
        TestEstimateView.as_view(),
        name="emptask_testing_estimate"
    ),
    url(r'dev/daily-effort/create/(?P<story_id>\d+)/$',
        DevelopmentEstimateCreateView.as_view(),
        name="emptask_development_estimate_create"
    ),
    url(r'test/daily-effort/create/(?P<story_id>\d+)/$',
        TestingEstimateCreateView.as_view(),
        name="emptask_testing_estimate_create"
    ),
    url(r'test/daily-effort/update/(?P<pk>\d+)/$',
        TestingEstimateUpdateView.as_view(),
        name="emptask_testing_estimate_update"
    ),
    url(r'dev/daily-effort/update/(?P<pk>\d+)/$',
        DevelopmentEstimateUpdateView.as_view(),
        name="emptask_development_estimate_update"
    ),
    url(r'$',
        EmployeeTaskTemplateView.as_view(),
        name="emptask_mytask"
    ),
]

hris/urls.py
from django.conf.urls import url
from hris.views import home
from hris.views import EmployeeCreateView
from hris.views import EmployeeDetailView
from hris.views import EmployeeListView
from hris.views import EmployeeUpdateView
from hris.views import EmployeeDeleteView

urlpatterns = [

    url(
        r'employee/update/(?P<pk>\d+)/$',
        EmployeeUpdateView.as_view(),
        name = "hris_employee_update"
    ),
    url(
        r'employee/delete/(?P<pk>\d+)/$',
        EmployeeDeleteView.as_view(),
        name = "hris_employee_delete"
    ),
    url(
        r'employee/detail/(?P<pk>\d+)/$',
        EmployeeDetailView.as_view(),
        name = "hris_employee_detail"
    ),
    url(
        r'employee/create/$',
        EmployeeCreateView.as_view(),
        name = "hris_employee_create"
    ),
    url(
        r'employee/$',
        EmployeeListView.as_view(),
        name = "hris_employee_list"
    ),
    url(
        r'$',
        home,
        name = "hris_home"
    ),
]

mumscrum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# from django.contrib.auth import login
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
from mumscrum.views.page_not_found_view import page_not_found_view
from mumscrum.views.bad_request_view import bad_request_view
from mumscrum.views.permission_denied_view import permission_denied_view
from mumscrum.views.server_error_view import server_error_view

handler400 = bad_request_view
handler404 = page_not_found_view
handler403 = permission_denied_view
handler500 = server_error_view

urlpatterns = [
    url(
        r'^login/$',
        'hris.views.auth.login',
        {'template_name' : 'auth/login.html'},
        name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(
        r'^reset/$',
        password_reset,
        {'template_name' : 'auth/password_reset_form.html'},        
        name='password_reset',
    ),

    url(
        r'^reset/done/$',
        password_reset_done,
        {'template_name' : 'auth/password_reset_done.html'},
        name='password_reset_done'
    ),    

    url(
        r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, 
        {'post_reset_redirect' : '/reset/complete/', 
            'template_name' : 'auth/password_reset_confirm.html' },
        name="password_reset_confirm"
    ),

    url(
        r'^reset/complete/$',
        password_reset_complete,
        {'template_name' : 'auth/password_reset_complete.html' },
        name='password_reset_complete'
    ),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^hris/', include("hris.urls")),
    url(r'^scrum/', include("scrum.urls")),
    url(r'^report/', include("report.urls")),
    url(r'^tasks/', include("emptask.urls")),
    url(r'^$', 'mumscrum.views.home', name='home'),
    # serving media files
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
    ]

emptask/models.py
from django.db import models

# Create your models here.

scrum/models/sprint.py
from django.db import models
from hris.models import Employee
from scrum.models import ReleaseBacklog

class Sprint(models.Model):
    name = models.CharField(
        max_length=50,
        null=False, blank=False,
        help_text = "Sprint name should be in order like Sprint-1, Sprint-2, and so on"
    )
    release_backlog = models.ForeignKey(
        ReleaseBacklog, null=False,
        blank=False
    )
    sprint_start = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    sprint_end = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    # object CRUD related infomation
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    created_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="sprint_created_by"
    )
    updated_on = models.DateTimeField(auto_now=True, auto_now_add=False)
    updated_by = models.ForeignKey(
        Employee, null=False,
        blank=False, related_name="sprint_updated_by"
    )
    is_deleted = models.BooleanField(default=False)
    deleted_on = models.DateTimeField(
        auto_now=False, auto_now_add=False,
        null=True, blank=True
    )
    deleted_by = models.ForeignKey(
        Employee, null=True,
        blank=True, related_name="sprint_deleted_by"
    )

    class Meta:
        app_label = 'scrum'

    def __unicode__(self):
        return self.name

    @property
    def product_backlog(self):
        return self.release_backlog.product_backlog
    

emptask/views/development_estimate_create_view.py
from django.views.generic.edit import CreateView
from scrum.models import WorkLog, UserStory
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.utils import timezone
from django.http import Http404

class DevelopmentEstimateCreateView(CreateView):
    model = WorkLog
    template_name = "emptask/development_estimate_daily_form.html"
    fields = ('work_remaining', 'work_done', 'description')

    @method_decorator(employee_role_required("developer"))
    def dispatch(self, *args, **kwargs):
        return super(DevelopmentEstimateCreateView, self).dispatch(*args, **kwargs)
    
    def get(self, *args, **kwargs):
        story_id = kwargs['story_id']        
        try:
            self.user_story = UserStory.objects.get(pk=story_id)
        except:
            raise Http404
        return super(DevelopmentEstimateCreateView, self).get(*args, **kwargs)

    def post(self, *args, **kwargs):
        story_id = kwargs['story_id']
        try:
            self.user_story = UserStory.objects.get(pk=story_id)
        except:
            raise Http404
        return super(DevelopmentEstimateCreateView, self).post(*args, **kwargs)

    def form_valid(self, form):
        form.instance.updated_by = self.request.user.employee
        form.instance.employee = self.request.user.employee
        form.instance.user_story = self.user_story
        form.instance.log_type = 'development'
        return super(DevelopmentEstimateCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(DevelopmentEstimateCreateView, self).get_context_data(**kwargs)
        context['user_story'] = self.user_story
        return context
    
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, \
            'Development Estimation successfully Updated'
        )
        success_url = reverse_lazy('emptask_development_task_detail', args=[self.user_story.id])
        return success_url

emptask/views/development_estimate_update_view.py
from django.views.generic.edit import UpdateView
from scrum.models import WorkLog, UserStory
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.utils import timezone
from django.http import Http404

class DevelopmentEstimateUpdateView(UpdateView):
    model = WorkLog
    template_name = "emptask/development_estimate_daily_form.html"
    fields = ('work_remaining', 'work_done', 'description')

    @method_decorator(employee_role_required("developer"))
    def dispatch(self, *args, **kwargs):
        return super(DevelopmentEstimateUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.updated_by = self.request.user.employee
        return super(DevelopmentEstimateUpdateView, self).form_valid(form)
    
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, \
            'Development Estimation successfully Updated'
        )
        success_url = reverse_lazy(
            'emptask_development_task_detail',
            args=[self.get_object().user_story.id]
        )
        return success_url

    def get_context_data(self, **kwargs):
        context = super(DevelopmentEstimateUpdateView, self).get_context_data(**kwargs)
        context['user_story'] = self.get_object().user_story
        return context

emptask/views/development_estimate_view.py
from django.views.generic.edit import UpdateView
from scrum.models import UserStory, WorkLog
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.utils import timezone

class DevelopmentEstimateView(UpdateView):
    model = UserStory
    template_name = "emptask/development_estimate_form.html"
    fields = ('developer_effort', )

    @method_decorator(employee_role_required("product_owner"))
    def dispatch(self, *args, **kwargs):
        return super(DevelopmentEstimateView, self).dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        form.instance.updated_by = self.request.user.employee
        worklog, created = WorkLog.objects.get_or_create(
            employee=self.request.user.employee,
            user_story=self.get_object(),
            date=timezone.now(),            
            log_type = 'development'
        )
        # import pdb;
        # pdb.set_trace()
        if created:
            worklog.created_by = self.request.user.employee
        worklog.work_remaining = form.cleaned_data['developer_effort']
        worklog.work_done = 0
        worklog.description = "User Story Task started"
        worklog.save()
        return super(DevelopmentEstimateView, self).form_valid(form)
        
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, \
            'Test Estimation successfully Updated'
        )
        success_url = reverse_lazy('emptask_mytask')
        return success_url

emptask/views/development_task_detail_view.py
from django.views.generic import DetailView
from scrum.models import UserStory
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.core.exceptions import PermissionDenied
from scrum.services import WorkLogService
from django.utils import timezone

class DevelopmentTaskDetailView(DetailView):
    model = UserStory
    template_name = "emptask/development_task_detail.html"

    @method_decorator(employee_role_required("developer"))
    def dispatch(self, *args, **kwargs):
        return super(DevelopmentTaskDetailView, self).dispatch(*args, **kwargs)

    def get(self, *args, **kwargs):
        instance = self.get_object()
        if not instance.assiged_developer == self.request.user.employee:
            raise PermissionDenied
        return super(DevelopmentTaskDetailView, self).get(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        today = timezone.now().date
        development_worklog =  WorkLogService.developer_worklogs(
            self.request.user.employee.id
        ).filter(user_story=self.get_object(), log_type="development")
        context = super(DevelopmentTaskDetailView, self).get_context_data(*args, **kwargs)
        context['today'] = today
        context['development_worklog'] = development_worklog
        context['log_exists_for_today'] =  development_worklog.filter(date=today).exists()
        context['user_story'] = self.get_object()
        return context

emptask/views/employee_tasks_view.py
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from scrum.models import WorkLog
from scrum.services import UserStoryService

class EmployeeTaskTemplateView(TemplateView):
    template_name = "emptask/employeetasks.html"
    
    @method_decorator(employee_role_required("developer", "tester"))
    def dispatch(self, *args, **kwargs):
        return super(EmployeeTaskTemplateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EmployeeTaskTemplateView, self).get_context_data(**kwargs)
        context['development_tasks'] = UserStoryService.developer_user_stories(
            self.request.user.employee.id
        ).order_by('sprint__id')
        context['testing_tasks'] = UserStoryService.tester_user_stories(
            self.request.user.employee.id
        ).order_by('sprint__id')
        return context

emptask/views/testing_estimate_create_view.py
from django.views.generic.edit import CreateView
from scrum.models import WorkLog, UserStory
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from hris.decorators import employee_role_required
from django.utils import timezone
from django.http import Http404

class TestingEstimateCreateView(CreateView):
    model = WorkLog
    template_name = "emptask/testing_estimate_daily_form.html"
    fields = ('work_remaining', 'work_done', 'description')

    @method_decorator(employee_role_required("tester"))
    def dispatch(self, *args, **kwargs):
        return super(TestingEstimateCreateView, self).dispatch(*args, **kwargs)
    
    def get(self, *args, **kwargs):
        story_id = kwargs['story_id']        
        try:
            self.user_story = UserStory.objects.get(pk=story_id)
        except:
            raise Http404
        return super(TestingEstimateCreateView, self).get(*args, **kwargs)

    def post(self, *args, **kwargs):
        story_id = kwargs['story_id']        
        try:
            self.user_story = UserStory.objects.get(pk=story_id)
        except:
            raise Http404
        return super(TestingEstimateCreateView, self).post(*args, **kwargs)

    def form_valid(self, form):
        form.instance.updated_by = self.request.user.employee
        form.instance.created_by = self.request.user.employee
        form.instance.employee = self.request.user.employee
        form.instance.user_story = self.user_story
        form.instance.log_type = 'test'
        return super(TestingEstimateCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(TestingEstimateCreateView, self).get_context_data(**kwargs)
        context['user_story'] = self.user_story
        return context
    
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, \
            'Testing Estimation successfully Updated'
        )
        success_url = reverse_lazy('emptask_testing_task_detail', args=[self.user_story.id])
        return success_url

emptask/templates/emptask/development_estimate_daily_form.html
{% extends "base.html"%}
{% block title %}{% endblock %}
{% block head %}{% endblock %}
<!-- This is page header and bredcrumb -->
{% block active_my_task %}active{% endblock %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Emptask
        <small>Control Panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'emptask_mytask' %}"><i class="fa fa-dashboard"></i> My Tasks</a></li>
        <li><a href="{% url 'emptask_development_task_detail' user_story.id %}">{{user_story.title}}</a></li>
        <li class="active">Estimate</li>
      </ol>
    </section>
{% endblock %}

<!-- Add your content here -->
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Estimate Development Task <small>{{user_story.title}}</small></h3>
      </div><!-- /.box-header -->
      <!-- form start -->
      <div class="row">
        
        <form class="col-md-8" action="" method="POST">
            <div class="box-body">
                {% csrf_token %}
                {% load bootstrap3 %}
                {% bootstrap_form form %}
            </div>
            <div class="box-footer">
              <a class="btn btn-default" href="{{request.META.HTTP_REFERER}}">Cancel</a>
              <button type="submit" class="btn btn-primary pull-right">Submit</button>
            </div><!-- /.box-footer -->
        </form>        
      </div>
    </div>
  </div>

</div>
{% endblock %} 
<!-- Add your javascript plugin src or code content here -->
{% block footer_js %}{% endblock %}

emptask/templates/emptask/development_estimate_form.html
{% extends "base.html"%}
{% block title %}{% endblock %}
{% block head %}{% endblock %}
<!-- This is page header and bredcrumb -->
{% block active_my_task %}active{% endblock %}
{% block content_header %}
    <section class="content-header">
      <h1>
        Emptask
        <small>Control Panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'emptask_mytask' %}"><i class="fa fa-dashboard"></i> My Tasks</a></li>
        <li><a href="{% url 'emptask_development_task_detail' object.id %}">{{object.title}}</a></li>
        <li class="active">Estimate</li>
      </ol>
    </section>
{% endblock %}

<!-- Add your content here -->
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Estimate Development Task <small>{{object.title}}</small></h3>
      </div><!-- /.box-header -->
      <!-- form start -->
      <div class="row">
        
        <form class="col-md-8" action="" method="POST">
            <div class="box-body">
                {% csrf_token %}
                {% load bootstrap3 %}
                {% bootstrap_form form %}
            </div>
            <div class="box-footer">
              <a class="btn btn-default" href="{{request.META.HTTP_REFERER}}">Cancel</a>
              <button type="submit" class="btn btn-primary pull-right">Submit</button>
            </div><!-- /.box-footer -->
        </form>        
      </div>
    </div>
  </div>

</div>
{% endblock %} 
<!-- Add your javascript plugin src or code content here -->
{% block footer_js %}{% endblock %}

emptask/templates/emptask/employeetasks.html
{% extends "base.html"%}
{% block title %}{% endblock %}
{% block head %}{% endblock %}
<!-- This is page header and bredcrumb -->
{% load employee_tags %}

{% block active_my_task %}active{% endblock %}

{% block content_header %}
    <section class="content-header">
      <h1>
        Employee Tasks
        <small>Tasks</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'hris_home' %}"><i class="fa fa-dashboard"></i> HRIS</a></li>
        <li class="active">Tasks</li>
      </ol>
    </section>
{% endblock %}
<!-- Add your content here -->
{% block content %}
<!-- EMPLOYEE LIST -->
{% ifrole DEVELOPER TESTER%}
<div class="row">
    {% ifrole TESTER %}
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Development Tasks List</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <tbody>
                            {% regroup development_tasks by product_backlog as product_list %}
                                {% for product in product_list %}
                                <tr>
                                    <td colspan="3">                                        
                                        <h3>{{ product.grouper }}</h3>
                                    </td>
                                </tr>
                                    {% regroup product.list by release_backlog as release_list %}
                                    {% for release in release_list %}
                                        <tr>
                                            <td colspan="3">                                        
                                                <h4>{{ release.grouper }}</h4>
                                            </td>
                                        </tr>
                                        {% regroup release.list by sprint as sprint_list %}
                                        {% for sprint in sprint_list %}
                                        <tr>
                                            <td colspan="3">                                        
                                                <h5>{{ sprint.grouper }}</h5>
                                            </td>
                                        </tr>
                                        {% for story in sprint.list %}
                                              <tr>
                                                <td width="15px"><b>{{forloop.counter}}.</b></td>
                                                <td class="mailbox-subject">
                                                    <a href="{% url 'emptask_development_task_detail' story.id %}">
                                                        <b>{{story.title}}</b>
                                                    </a>
                                                    -{{story.description|truncatechars:30}}
                                                </td>
                                                <td>
                                                    <label class="badge badge-info">
                                                    {% if story.developer_effort %}
                                                        {{story.developer_effort}} hours
                                                    {% else %}
                                                        Not estimated
                                                    {% endif %}
                                                    </label>
                                                </td>
                                                <td>
                                                    {% if story.developer_effort == None %}
                                                        <a href="{% url 'emptask_development_estimate' story.id %}" title="Click to start task" data-toggle="tooltip"><i class="fa fa-times-circle icon-delete" ></i></a>
                                                    {% else %}
                                                        <a href="{% url 'emptask_development_estimate' story.id %}" title="Click to change estimation" data-toggle="tooltip"><i class="fa fa-check-circle icon-edit" ></i></a>
                                                    {% endif %}
                                                </td>
                                              </tr>
                                            {% endfor %}
                                        {% endfor %}
                                    {% endfor %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endifrole %}
    {% ifrole DEVELOPER %}
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Testing Tasks List</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <tbody>
                            {% regroup testing_tasks by product_backlog as product_list %}
                                {% for product in product_list %}
                                <tr>
                                    <td colspan="3">                                        
                                        <h3>{{ product.grouper }}</h3>
                                    </td>
                                </tr>
                                    {% regroup product.list by release_backlog as release_list %}
                                    {% for release in release_list %}
                                        <tr>
                                            <td colspan="3">                                        
                                                <h4>{{ release.grouper }}</h4>
                                            </td>
                                        </tr>
                                        {% regroup release.list by sprint as sprint_list %}
                                        {% for sprint in sprint_list %}
                                        <tr>
                                            <td colspan="3">                                        
                                                <h5>{{ sprint.grouper }}</h5>
                                            </td>
                                        </tr>
                                        {% for story in sprint.list %}
                                              <tr>
                                                <td width="15px"><b>{{forloop.counter}}.</b></td>
                                                <td class="mailbox-subject">
                                                    <a href="{% url 'emptask_testing_task_detail' story.id %}">
                                                        <b>{{story.title}}</b>
                                                    </a>
                                                    -{{story.description|truncatechars:30}}
                                                </td>
                                                <td>
                                                    <label class="badge badge-info">
                                                    {% if story.tester_effort %}
                                                        {{story.tester_effort}} hours
                                                    {% else %}
                                                        Not estimated
                                                    {% endif %}
                                                    </label>
                                                </td>
                                                <td>
                                                    {% if story.tester_effort == None %}
                                                        <a href="{% url 'emptask_testing_estimate' story.id %}" title="Click to start task" data-toggle="tooltip"><i class="fa fa-times-circle icon-delete" ></i></a>
                                                    {% else %}
                                                        <a href="{% url 'emptask_testing_estimate' story.id %}" title="Click to change estimation" data-toggle="tooltip"><i class="fa fa-check-circle icon-edit" ></i></a>
                                                    {% endif %}
                                                </td>
                                              </tr>
                                            {% endfor %}
                                        {% endfor %}
                                    {% endfor %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>  
    {% endifrole %}
</div>
{% endifrole %}        

{% endblock %} 
<!-- Add your javascript plugin src or code content here -->
{% block footer_js %}
{% endblock %}